### ISSUE TITLE
CodeBuild error

### ISSUE THREAD

**Issue by mguajardo** [awslabs/aws-full-stack-template#4]
Hi,
After just running the cloudFormation stack for the first time I got an error in the CodePipeline build phase. No commits beside the initial one from the stack.
CodeBuild log show the following:

...
Creating an optimized production build... 
Failed to compile. 
 
/codebuild/output/src975068437/src/node_modules/@aws-amplify/api/lib/API.d.ts 
TypeScript error: Could not find a declaration file for module 'zen-observable'. '/codebuild/output/src975068437/src/node_modules/zen-observable/index.js' implicitly has an 'any' type. 
  Try `npm install @types/zen-observable` if it exists or add a new declaration (.d.ts) file containing `declare module 'zen-observable';`  TS7016 
 
  > 1 | import * as Observable from 'zen-observable'; 
      |                             ^ 
    2 | import { GraphQLOptions, GraphQLResult } from './types'; 
    3 | export declare const graphqlOperation: (query: any, variables?: {}) => { 
    4 |     query: any; 
 
 
 
npm ERR! Linux 4.14.123-86.109.amzn1.x86_64 
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build" 
npm ERR! node v7.0.0 
npm ERR! npm  v3.10.8 
npm ERR! code ELIFECYCLE 
npm ERR! marvin-2.0@0.1.0 build: `react-scripts build` 
npm ERR! Exit status 1 
npm ERR!  
npm ERR! Failed at the marvin-2.0@0.1.0 build script 'react-scripts build'. 
npm ERR! Make sure you have the latest version of node.js and npm installed. 
npm ERR! If you do, this is most likely a problem with the marvin-2.0 package, 
npm ERR! not with npm itself. 
npm ERR! Tell the author that this fails on your system: 
npm ERR!     react-scripts build 
npm ERR! You can get information on how to open an issue for this project with: 
npm ERR!     npm bugs marvin-2.0 
npm ERR! Or if that isn't available, you can get their info via: 
npm ERR!     npm owner ls marvin-2.0 
npm ERR! There is likely additional logging output above. 
 
npm ERR! Please include the following file with any support request: 
npm ERR!     /codebuild/output/src975068437/src/npm-debug.log 
 
[Container] 2019/07/20 22:55:13 Command did not exit successfully npm run build exit status 1 
[Container] 2019/07/20 22:55:13 Phase complete: BUILD State: FAILED 
[Container] 2019/07/20 22:55:13 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npm run build. Reason: exit status 1 
[Container] 2019/07/20 22:55:13 Entering phase POST_BUILD 
[Container] 2019/07/20 22:55:13 Running command echo Uploading to AssetsBucket 
...

Clonning the repo and running in local works fine

**Comment by smohiuddin** [comment]
Hi, 

Thanks for filing an issue. We have updated the package.json to fix the issue. Please re-deploy the template to get the latest code.
